services:
  discord-bot:
    container_name: discord-bot
    image: discord-bot:latest
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - default
      - services-proxy
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1:8080/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  default:
    name: discord-bot-network
    external: true
  services-proxy:
    external: true
