services:
  discord-bot:
    container_name: discord-bot
    build:
      context: .
      dockerfile: Dockerfile
      target: develop
    volumes:
      - ./:/app
      - bot-cargo-registry:/usr/local/cargo/registry
      - bot-cargo-git:/usr/local/cargo/git
      - bot-target:/app/target
    env_file:
      - .env
    command: ["cargo", "watch", "-x", "run --bin discord-bot"]
    ports:
      - "8080:8080"
    depends_on:
      ready_checker:
        condition: service_completed_successfully

  ready_checker:
    extends:
      file: docker-compose.db.yml
      service: ready_checker

  mongo:
    extends:
      file: docker-compose.db.yml
      service: mongo
  
  mongo-setup:
    extends:
      file: docker-compose.db.yml
      service: mongo-setup

  redis:
    extends:
      file: docker-compose.db.yml
      service: redis

networks:
  default:
    name: discord-bot-network
    external: true

volumes:
  bot-cargo-registry:
  bot-cargo-git:
  bot-target:
