services:
  ready_checker:
    image: alpine
    depends_on:
      mongo-setup:
        condition: service_completed_successfully
      redis:
        condition: service_healthy

  mongo:
    image: mongo:7
    container_name: mongo
    command: ["mongod", "-f", "/cfg/mongod.conf"]
    volumes:
      - ./.mongodb/cfg/mongod.conf:/cfg/mongod.conf
    healthcheck:
      test: ["CMD", "mongosh", "--host", "mongo:27017", "--eval", "rs.isMaster().ismaster"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  mongo-setup:
    image: mongo:7
    container_name: mongo-setup
    command: ["mongosh", "--host", "mongo:27017", "/cfg/init-mongo.js"]
    volumes:
      - ./.mongodb/cfg/mongod.conf:/cfg/mongod.conf
      - ./.mongodb/cfg/init-mongo.js:/cfg/init-mongo.js
    depends_on:
      mongo:
        condition: service_healthy

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
    name: discord-bot-network
    external: true
