FROM rust:alpine
                                                  
RUN apk add --no-cache \
    pkgconf \
    openssl-dev \
    openssl-libs-static \
    build-base 

WORKDIR /usr/src/discord-bot

RUN cargo install cargo-watch                                                      
